/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class raw_root_Data */

#ifndef _Included_raw_root_Data
#define _Included_raw_root_Data
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     raw_root_Data
 * Method:    getTypeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_raw_root_Data_getTypeName
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getType
 * Signature: ()Lraw/root/Data/DataType;
 */
JNIEXPORT jobject JNICALL Java_raw_root_Data_getType
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_raw_root_Data_getByte
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getInt32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_raw_root_Data_getInt32
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_raw_root_Data_getLong
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_raw_root_Data_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_raw_root_Data_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_raw_root_Data_getString
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_raw_root_Data_initialize
  (JNIEnv *, jobject);

/*
 * Class:     raw_root_Data
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_raw_root_Data_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
