/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class raw_root_Inferrer */

#ifndef _Included_raw_root_Inferrer
#define _Included_raw_root_Inferrer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     raw_root_Inferrer
 * Method:    InferScheme
 * Signature: (Ljava/lang/String;)Lraw/root/types/Type;
 */
JNIEXPORT jobject JNICALL Java_raw_root_Inferrer_infer
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
